/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v6.0
processor: LPC845
package_id: LPC845M301JBD48
mcu_data: ksdk2_0
processor_version: 6.0.2
board: LPC845BREAKOUT
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA_1'
- type: 'lpc_dma'
- mode: 'basic'
- type_id: 'lpc_dma_77c87b8df0796f4146842e3f11ac40fe'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
    - init_interrupt: 'false'
    - dma_interrupt:
      - IRQn: 'DMA0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - dma_channels:
      - 0:
        - dma_channel:
          - channel_prefix_id: 'dma_usart'
          - DMA_source: 'kDmaRequestUSART0_RX_DMA '
          - enable_custom_name: 'false'
        - init_callback: 'true'
        - callback_function: 'callback_dma0'
        - callback_user_data: ''
        - peripheral_request: 'false'
        - init_trigger_config: 'true'
        - trigger_config:
          - type: 'kDMA_NoTrigger'
          - burst: 'kDMA_SingleTransfer'
          - wrap: 'kDMA_NoWrap'
        - init_channel_priority: 'true'
        - channel_priority: 'kDMA_ChannelPriority0'
        - enable_interrupt: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

  /* Channel dma_usart global variables */
dma_handle_t DMA_1_dma_usart_Handle;
const dma_channel_trigger_t DMA_1_dma_usart_trigger_config = {
  .type = kDMA_NoTrigger,
  .burst = kDMA_SingleTransfer,
  .wrap = kDMA_NoWrap
};

void DMA_1_init(void) {

  /* Channel dma_usart initialization */
  /* Enable the 0 channel in the DMA */
  DMA_EnableChannel(DMA_1_DMA_BASEADDR, DMA_1_DMA_USART_DMA_CHANNEL);
  /* Create the DMA DMA_1_dma_usart_Handle handle */
  DMA_CreateHandle(&DMA_1_dma_usart_Handle, DMA_1_DMA_BASEADDR, DMA_1_DMA_USART_DMA_CHANNEL);
  DMA_SetCallback(&DMA_1_dma_usart_Handle, callback_dma0, NULL);
  /* Configuration of the channel trigger and peripheral request */
  DMA_SetChannelConfig(DMA_1_DMA_BASEADDR, DMA_1_DMA_USART_DMA_CHANNEL, (dma_channel_trigger_t *)&DMA_1_dma_usart_trigger_config, false);
  DMA_SetChannelPriority(DMA_1_DMA_BASEADDR, DMA_1_DMA_USART_DMA_CHANNEL, kDMA_ChannelPriority0);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMA_Init(DMA_1_DMA_BASEADDR);

  /* Initialize components */
  DMA_1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
