/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_mrt.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for USART1 */
/* Definition of peripheral ID */
#define UBLOXUSARTGPS_PERIPHERAL ((USART_Type *)USART1)
/* Definition of the clock source frequency */
#define UBLOXUSARTGPS_CLOCK_SOURCE 15000000UL
/* UbloxUsartGPS interrupt vector ID (number). */
#define UBLOXUSARTGPS_USART_IRQN USART1_IRQn
/* UbloxUsartGPS interrupt handler identifier. */
#define UbloxUsartGPS_IRQHandler USART1_IRQHandler
/* BOARD_InitPeripherals defines for USART2 */
/* Definition of peripheral ID */
#define TELITUSARTGSM_PERIPHERAL ((USART_Type *)USART2)
/* Definition of the clock source frequency */
#define TELITUSARTGSM_CLOCK_SOURCE 15000000UL
/* TelitUsartGSM interrupt vector ID (number). */
#define TELITUSARTGSM_USART_IRQN USART2_IRQn
/* TelitUsartGSM interrupt handler identifier. */
#define TelitUsartGSM_IRQHandler USART2_IRQHandler
/* Definition of peripheral ID */
#define MRT_1_PERIPHERAL MRT0
/* Definition of channel 0 ID */
#define MRT_1_CHANNEL_0 kMRT_Channel_0
/* Definition of channel 0 mode */
#define MRT_1_CHANNEL_0_MODE kMRT_RepeatMode
/* Definition of channel 0 timer in ticks */
#define MRT_1_CHANNEL_0_TICKS 1000000U
/* MRT_1 interrupt vector ID (number). */
#define MRT_1_IRQN MRT0_IRQn
/* MRT_1 interrupt handler identifier. */
#define MRT_1_IRQHANDLER MRT0_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const usart_config_t UbloxUsartGPS_config;
extern const usart_config_t TelitUsartGSM_config;
extern const mrt_config_t MRT_1_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
